// Auto-generated by cft from: test.c
// May require manual edits.

struct Vector;
cdecl{}* FreeFunc(void* dat) -> void;

cdecl{}* CompareFunc(void* a, void* b) -> int;

cdecl vector_resize(Vector* v, int capacity) -> void
{
    void** items = realloc(v.items, (sizeof ( void * ) / 8) * capacity);
    if (items)
    {
        v.items = items;
        v.capacity = capacity;
    };
};

cdecl vector_add(Vector* v, void* item) -> void
{
    if (v.capacity == v.total)
    {
        vector_resize(v, v.capacity * 2);
    };
    v.items[v.total++] = item;
};

cdecl vector_get(Vector* v, int index) -> void*
{
    if (index >= 0 & index < v.total)
    {
        return v.items[index];
    };
    return ((void*)0);
};

cdecl vector_sort(Vector* v, def{}*(void*, void*) -> int comp) -> void
{
    if (v.items & v.total > 0)
    {
        qsort(v.items, v.total, (sizeof ( void * ) / 8), comp);
    };
};

cdecl vector_free(Vector* v, def{}*(void*) -> void free_item) -> void
{
    if (!v)
        return void;
    if (free_item)
    {
        for (int i = 0; i < v.total; i++)
        {
            free_item(v.items[i]);
        };
    };
    free(v.items);
    free(v);
};

cdecl create_vector(int initial_capacity) -> Vector*
{
    Vector* v = malloc((sizeof ( Vector ) / 8));
    if (!v)
        return ((void*)0);
    v.capacity = initial_capacity > 0 ? initial_capacity : 4;
    v.total = 0;
    v.items = malloc((sizeof ( void * ) / 8) * v.capacity);
    v.add = vector_add;
    v.get = vector_get;
    v.sort = vector_sort;
    v.free = vector_free;
    return v;
};

struct Player
{
    byte[32] name;
    int score;
};

cdecl compare_players(void* a, void* b) -> int
{
    Player* playerA = ?(Player**)a;
    Player* playerB = ?(Player**)b;
    return playerB.score - playerA.score;
};

cdecl main() -> int
{
    Vector* player_list = create_vector(2);
    Player* p1 = malloc((sizeof ( Player ) / 8));
    strcpy(p1.name, "Alice");
    p1.score = 95;
    Player* p2 = malloc((sizeof ( Player ) / 8));
    strcpy(p2.name, "Bob");
    p2.score = 88;
    Player* p3 = malloc((sizeof ( Player ) / 8));
    strcpy(p3.name, "Charlie");
    p3.score = 99;
    player_list.add(player_list, p1);
    player_list.add(player_list, p2);
    player_list.add(player_list, p3);
    player_list.sort(player_list, compare_players);
    printf("Leaderboard:\n");
    for (int i = 0; i < player_list.total; i++)
    {
        Player* p = (Player*)player_list.get(player_list, i);
        printf("%d. %s - %d\n", i + 1, p.name, p.score);
    };
    player_list.free(player_list, free);
    return 0;
};
