#import <standard.fx>;
using standard::io::console;

comptime
{
    // First layer: generate N "generator" functions
    int i, N = 3;

    for (i = 0; i < N; i++)
    {
        emitflux
        {
            // Each generator function emits MORE functions
            def ~$i"gen_layer_{}":{i;}(int x) -> void
            {
                comptime
                {
                    emitflux
                    {
                        def ~$i"hello_from_layer_{}":{x;}() -> void
                        {
                            println(f"Hello from layer {x}");
                        };
                    };
                };
            };

            ~$f"gen_layer_{i}({i});";
        };
    };
};

// Call the generator functions — they emit new functions at compile time
gen_layer_0(0);
gen_layer_1(1);
gen_layer_2(2);

def main() -> int
{

    // Now call the functions generated BY those functions
    hello_from_layer_0();
    hello_from_layer_1();
    hello_from_layer_2();

    return 0;
};
